services:
  postgres:
    image: postgres:latest
    container_name: next-template-db
    restart: unless-stopped
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next_template
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
